import java.awt.print.PrinterException;
import java.text.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

public class CashierApp extends JFrame {
    /**
     * Creates new form CashierApp
     */
    public CashierApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonPencil = new javax.swing.JButton();
        jButtonMechanical = new javax.swing.JButton();
        jButtonFountain = new javax.swing.JButton();
        jButtonSharpener = new javax.swing.JButton();
        jButtonEraser = new javax.swing.JButton();
        jButtonColorPencil = new javax.swing.JButton();
        jButtonCharcoal = new javax.swing.JButton();
        jButtonBox = new javax.swing.JButton();
        jButtonLead = new javax.swing.JButton();
        jButtonCalculator = new javax.swing.JButton();
        jButtonPen = new javax.swing.JButton();
        jButtonCaryon = new javax.swing.JButton();
        jButtonDucttape = new javax.swing.JButton();
        jButtonStapler = new javax.swing.JButton();
        jButtonBrushes = new javax.swing.JButton();
        jButtonPaper = new javax.swing.JButton();
        jButtonScissors = new javax.swing.JButton();
        jButtonTape = new javax.swing.JButton();
        jButtonGlue = new javax.swing.JButton();
        jButtonBook = new javax.swing.JButton();
        jButtonMarker = new javax.swing.JButton();
        jButtonWatercolor = new javax.swing.JButton();
        jButtonStaplet = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton07 = new javax.swing.JButton();
        jButton09 = new javax.swing.JButton();
        jButton08 = new javax.swing.JButton();
        jButton04 = new javax.swing.JButton();
        jButton05 = new javax.swing.JButton();
        jButton06 = new javax.swing.JButton();
        jButton01 = new javax.swing.JButton();
        jButton02 = new javax.swing.JButton();
        jButton03 = new javax.swing.JButton();
        jButton00 = new javax.swing.JButton();
        jButtonPeriod = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextDisplay = new javax.swing.JTextField();
        jTextChange = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboPayment = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextTotal = new javax.swing.JTextField();
        jTextSubtotal = new javax.swing.JTextField();
        jTextDiscount = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jButtonPay = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPencil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPencil.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPencil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pencil_90x100.jpg"))); // NOI18N
        jButtonPencil.setText("RM0.60");
        jButtonPencil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPencil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPencil.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonPencil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPencilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPencil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 100));

        jButtonMechanical.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonMechanical.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMechanical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/istockphoto-1298259761-612x612_90x100.jpg"))); // NOI18N
        jButtonMechanical.setText("RM 2.70");
        jButtonMechanical.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonMechanical.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMechanical.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonMechanical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMechanicalActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMechanical, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 100));

        jButtonFountain.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFountain.setForeground(new java.awt.Color(255, 51, 51));
        jButtonFountain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fountain pen.jpg"))); // NOI18N
        jButtonFountain.setText("RM 4.50");
        jButtonFountain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonFountain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFountain.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonFountain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFountainActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFountain, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 90, 100));

        jButtonSharpener.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSharpener.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSharpener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sharpener.jpg"))); // NOI18N
        jButtonSharpener.setText("RM 0.20");
        jButtonSharpener.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSharpener.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSharpener.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonSharpener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSharpenerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSharpener, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 90, 100));

        jButtonEraser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonEraser.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEraser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eras.jpg"))); // NOI18N
        jButtonEraser.setText("RM 0.80");
        jButtonEraser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEraser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEraser.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonEraser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEraserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEraser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, 100));

        jButtonColorPencil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonColorPencil.setForeground(new java.awt.Color(255, 255, 255));
        jButtonColorPencil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/color_90x100.jpg"))); // NOI18N
        jButtonColorPencil.setText("RM 6.50");
        jButtonColorPencil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonColorPencil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonColorPencil.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonColorPencil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorPencilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonColorPencil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 100));

        jButtonCharcoal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCharcoal.setForeground(new java.awt.Color(102, 204, 255));
        jButtonCharcoal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nS6OlYdODwtePq9B7pEB9bjiFeZjZOhxSnNs0UOI_90x100.jpeg"))); // NOI18N
        jButtonCharcoal.setText("RM 0.80");
        jButtonCharcoal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCharcoal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCharcoal.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonCharcoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCharcoalActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCharcoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 100));

        jButtonBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBox.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.jpg"))); // NOI18N
        jButtonBox.setText("RM 6.80");
        jButtonBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBox.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 90, 100));

        jButtonLead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonLead.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lead.jpg"))); // NOI18N
        jButtonLead.setText("RM 0.90");
        jButtonLead.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLead.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLead.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonLead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeadActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLead, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 90, 100));

        jButtonCalculator.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCalculator.setForeground(new java.awt.Color(204, 204, 0));
        jButtonCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calculator.jpg"))); // NOI18N
        jButtonCalculator.setText("RM 15.90");
        jButtonCalculator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCalculator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCalculator.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculatorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCalculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 90, 100));

        jButtonPen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPen.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gel.jpg"))); // NOI18N
        jButtonPen.setText("RM 2.60");
        jButtonPen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPen.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPenActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 90, 100));

        jButtonCaryon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCaryon.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCaryon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Jumbo-Crayons-Wholesale-Caryon-Sets-for-Children-Art-Painting_90x100.jpg"))); // NOI18N
        jButtonCaryon.setText("RM 5.80");
        jButtonCaryon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCaryon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCaryon.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonCaryon.setVerifyInputWhenFocusTarget(false);
        jButtonCaryon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaryonActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCaryon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 90, 100));

        jButtonDucttape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonDucttape.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDucttape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/duct tape.jpg"))); // NOI18N
        jButtonDucttape.setText("RM 1.60");
        jButtonDucttape.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDucttape.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDucttape.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonDucttape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDucttapeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDucttape, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 90, 100));

        jButtonStapler.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonStapler.setForeground(new java.awt.Color(0, 0, 0));
        jButtonStapler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image_processing20211006-8971-17guvx1_90x100.jpg"))); // NOI18N
        jButtonStapler.setText("RM 3.00");
        jButtonStapler.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonStapler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStapler.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonStapler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStaplerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonStapler, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 90, 100));

        jButtonBrushes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBrushes.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBrushes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brushes.jpg"))); // NOI18N
        jButtonBrushes.setText("RM 1.70");
        jButtonBrushes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBrushes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBrushes.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonBrushes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrushesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBrushes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 90, 100));

        jButtonPaper.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPaper.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/a4 paper.jpeg"))); // NOI18N
        jButtonPaper.setText("RM 18.50");
        jButtonPaper.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPaper.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPaper.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaperActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 90, 100));

        jButtonScissors.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonScissors.setForeground(new java.awt.Color(255, 0, 255));
        jButtonScissors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/scissors.jpg"))); // NOI18N
        jButtonScissors.setText("RM 2.00");
        jButtonScissors.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonScissors.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonScissors.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonScissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonScissorsActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonScissors, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 90, 100));

        jButtonTape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonTape.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transparent tape.jpg"))); // NOI18N
        jButtonTape.setText("RM 1.00");
        jButtonTape.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonTape.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTape.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonTape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTapeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTape, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 90, 100));

        jButtonGlue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonGlue.setForeground(new java.awt.Color(0, 0, 0));
        jButtonGlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/glue.jpg"))); // NOI18N
        jButtonGlue.setText("RM 2.00");
        jButtonGlue.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGlue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGlue.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonGlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGlueActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 90, 100));

        jButtonBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBook.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excercise book.jpg"))); // NOI18N
        jButtonBook.setText("RM 1.10");
        jButtonBook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBook.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 90, 100));

        jButtonMarker.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonMarker.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMarker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/marker.jpg"))); // NOI18N
        jButtonMarker.setText("RM 1.20");
        jButtonMarker.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonMarker.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMarker.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonMarker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarkerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMarker, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 90, 100));

        jButtonWatercolor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonWatercolor.setForeground(new java.awt.Color(0, 0, 0));
        jButtonWatercolor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/water color.jpg"))); // NOI18N
        jButtonWatercolor.setText("RM 7.80");
        jButtonWatercolor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonWatercolor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonWatercolor.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonWatercolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWatercolorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonWatercolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 90, 100));

        jButtonStaplet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonStaplet.setForeground(new java.awt.Color(0, 0, 0));
        jButtonStaplet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/staplet.jpg"))); // NOI18N
        jButtonStaplet.setText("RM 0.50");
        jButtonStaplet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonStaplet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStaplet.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonStaplet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStapletActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonStaplet, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 90, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 630, 450));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton07.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton07.setText("7");
        jButton07.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton07.setPreferredSize(new java.awt.Dimension(75, 80));
        jButton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton07ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton07, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 100));

        jButton09.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton09.setText("9");
        jButton09.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton09.setPreferredSize(new java.awt.Dimension(75, 80));
        jButton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton09ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton09, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 100));

        jButton08.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton08.setText("8");
        jButton08.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton08.setPreferredSize(new java.awt.Dimension(75, 80));
        jButton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton08ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton08, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 100));

        jButton04.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton04.setText("4");
        jButton04.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton04.setPreferredSize(new java.awt.Dimension(75, 80));
        jButton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton04ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton04, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, 100));

        jButton05.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton05.setText("5");
        jButton05.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton05.setPreferredSize(new java.awt.Dimension(75, 80));
        jButton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton05ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton05, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, 100));

        jButton06.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton06.setText("6");
        jButton06.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton06.setPreferredSize(new java.awt.Dimension(75, 80));
        jButton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton06ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton06, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 90, 100));

        jButton01.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton01.setText("1");
        jButton01.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton01.setPreferredSize(new java.awt.Dimension(75, 80));
        jButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton01ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 90, 100));

        jButton02.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton02.setText("2");
        jButton02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton02.setPreferredSize(new java.awt.Dimension(75, 80));
        jButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton02ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton02, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 90, 100));

        jButton03.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton03.setText("3");
        jButton03.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton03.setPreferredSize(new java.awt.Dimension(75, 80));
        jButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton03ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton03, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 90, 100));

        jButton00.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton00.setText("0");
        jButton00.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton00.setPreferredSize(new java.awt.Dimension(75, 80));
        jButton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton00ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton00, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, 100));

        jButtonPeriod.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonPeriod.setText(".");
        jButtonPeriod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPeriod.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeriodActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 90, 100));

        jButtonCancel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonCancel.setText("C");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(75, 80));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 90, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 450));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Amount"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 360, 450));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Payment Method");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Cash");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 30));

        jTextDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDisplayActionPerformed(evt);
            }
        });
        jPanel3.add(jTextDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 200, 40));

        jTextChange.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextChangeActionPerformed(evt);
            }
        });
        jPanel3.add(jTextChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Change");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        jComboPayment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jComboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit", "Credit", "QR Pay" }));
        jComboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPaymentActionPerformed(evt);
            }
        });
        jPanel3.add(jComboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 200, 40));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 440, 200));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Total");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Subtotal");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Discount");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        jTextTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel5.add(jTextTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 200, 40));

        jTextSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSubtotalActionPerformed(evt);
            }
        });
        jPanel5.add(jTextSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 200, 40));

        jTextDiscount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel5.add(jTextDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 200, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 200));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonExit.setText("EXIT");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 420, 60));

        jButtonPay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPay.setText("PAY");
        jButtonPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        jButtonReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonReset.setText("RESET");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 200, 50));

        jButtonRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonRemove.setText("REMOVE");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 200, 50));

        jButtonPrint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPrint.setText("PRINT");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 50));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 440, 200));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 1350, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ItemCost() {
        double sum = 0;
        
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        jTextSubtotal.setText(Double.toString(sum));
        double cTextTotal = Double.parseDouble(jTextSubtotal.getText());
        
        double cTextDiscount = (cTextTotal * (3.60 / 100));
        String iTextTotal = String.format("RM %.2f", cTextDiscount);
        jTextDiscount.setText(iTextTotal);
                
        String iTextSubtotal = String.format("RM %.2f", cTextTotal);
        jTextSubtotal.setText(iTextSubtotal);
        
        String iTotal = String.format("RM %.2f", cTextTotal - cTextDiscount);
        jTextTotal.setText(iTotal);
    }
    
    public void Change() {
        double sum = 0;
        double cash = Double.parseDouble(jTextDisplay.getText());
        
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        double cTextDiscount = (sum / 3.60)/100;
        double cChange = (cash - (sum + cTextDiscount));
        
        String ChangeGiven = String.format("RM %.2f", cChange);
        jTextChange.setText(ChangeGiven);
    }
    private void jButton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton08ActionPerformed
        String Enternumber = jTextDisplay.getText();
        
        if (Objects.equals(Enternumber, "")) {
            jTextDisplay.setText(jButton08.getText());
        }
        else {
            Enternumber = jTextDisplay.getText() + jButton08.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton08ActionPerformed

    private void jButton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton05ActionPerformed
        String Enternumber = jTextDisplay.getText();
        
        if (Objects.equals(Enternumber, "")) {
            jTextDisplay.setText(jButton05.getText());
        }
        else {
            Enternumber = jTextDisplay.getText() + jButton05.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton05ActionPerformed

    private void jButton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton02ActionPerformed
        String Enternumber = jTextDisplay.getText();
        
        if (Objects.equals(Enternumber, "")) {
            jTextDisplay.setText(jButton02.getText());
        }
        else {
            Enternumber = jTextDisplay.getText() + jButton02.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton02ActionPerformed

    private void jButtonPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeriodActionPerformed
        if (! jTextDisplay.getText().contains(".")); {
        jTextDisplay.setText(jTextDisplay.getText() + jButtonPeriod.getText());
    }
    }//GEN-LAST:event_jButtonPeriodActionPerformed

    private void jButtonMechanicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMechanicalActionPerformed
        double priceOfItem = 2.70;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Mechanical Pencil: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonMechanicalActionPerformed

    private void jButtonEraserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEraserActionPerformed
        double priceOfItem = 0.80;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Eraser: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonEraserActionPerformed

    private void jButtonLeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeadActionPerformed
        double priceOfItem = 0.90;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Pencil Lead: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonLeadActionPerformed

    private void jButtonPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPenActionPerformed
        double priceOfItem = 2.60;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Pen: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonPenActionPerformed

    private void jButtonStaplerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStaplerActionPerformed
        double priceOfItem = 3.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Stapler: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonStaplerActionPerformed

    private void jButtonScissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonScissorsActionPerformed
        double priceOfItem = 2.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Scissors: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonScissorsActionPerformed

    private void jButtonMarkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarkerActionPerformed
        double priceOfItem = 1.20;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Whiteboard Marker: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonMarkerActionPerformed

    private void jButtonWatercolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWatercolorActionPerformed
        double priceOfItem = 7.80;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Watercolor: 1 box", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonWatercolorActionPerformed

    private void jTextDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDisplayActionPerformed

    private void jComboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboPaymentActionPerformed

    private void jButtonPencilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPencilActionPerformed
        double priceOfItem = 0.60;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Pencil: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonPencilActionPerformed

    private void jButtonColorPencilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorPencilActionPerformed
        double priceOfItem = 6.50;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Color Pencil: 1 box", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonColorPencilActionPerformed

    private void jButton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton07ActionPerformed
        String Enternumber = jTextDisplay.getText();
        
        if (Objects.equals(Enternumber, "")) {
            jTextDisplay.setText(jButton07.getText());
        }
        else {
            Enternumber = jTextDisplay.getText() + jButton07.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton07ActionPerformed

    private void jButton09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton09ActionPerformed
        String Enternumber = jTextDisplay.getText();
        
        if (Objects.equals(Enternumber, "")) {
            jTextDisplay.setText(jButton09.getText());
        }
        else {
            Enternumber = jTextDisplay.getText() + jButton09.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton09ActionPerformed

    private void jButton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton04ActionPerformed
        String Enternumber = jTextDisplay.getText();
        
        if (Objects.equals(Enternumber, "")) {
            jTextDisplay.setText(jButton04.getText());
        }
        else {
            Enternumber = jTextDisplay.getText() + jButton04.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton04ActionPerformed

    private void jButton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton06ActionPerformed
        String Enternumber = jTextDisplay.getText();
        
        if (Objects.equals(Enternumber, "")) {
            jTextDisplay.setText(jButton06.getText());
        }
        else {
            Enternumber = jTextDisplay.getText() + jButton06.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton06ActionPerformed

    private void jButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton01ActionPerformed
        String Enternumber = jTextDisplay.getText();
        
        if (Objects.equals(Enternumber, "")) {
            jTextDisplay.setText(jButton01.getText());
        }
        else {
            Enternumber = jTextDisplay.getText() + jButton01.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton01ActionPerformed

    private void jButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton03ActionPerformed
        String Enternumber = jTextDisplay.getText();
        
        if (Objects.equals(Enternumber, "")) {
            jTextDisplay.setText(jButton03.getText());
        }
        else {
            Enternumber = jTextDisplay.getText() + jButton03.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton03ActionPerformed

    private void jButton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton00ActionPerformed
        String Enternumber = jTextDisplay.getText();
        
        if (Objects.equals(Enternumber, "")) {
            jTextDisplay.setText(jButton00.getText());
        }
        else {
            Enternumber = jTextDisplay.getText() + jButton00.getText();
            jTextDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jButton00ActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        jTextDisplay.setText("");
        jTextChange.setText("");
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayActionPerformed
        if (jComboPayment.getSelectedItem().equals("Cash")) {
            Change();
        } 
        
        else {
            jTextChange.setText("");
            jTextDisplay.setText("");
        }
    }//GEN-LAST:event_jButtonPayActionPerformed

    private void jButtonCharcoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCharcoalActionPerformed
        double priceOfItem = 0.80;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Charcoal: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonCharcoalActionPerformed

    private void jButtonCaryonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaryonActionPerformed
        double priceOfItem = 5.80;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Crayon: 1 box", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonCaryonActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
    
    }//GEN-LAST:event_jTable1KeyPressed

    private void jButtonFountainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFountainActionPerformed
        double priceOfItem = 4.50;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Fountain Pen: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonFountainActionPerformed

    private void jButtonSharpenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSharpenerActionPerformed
        double priceOfItem = 0.20;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Sharpener: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonSharpenerActionPerformed

    private void jButtonBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBoxActionPerformed
        double priceOfItem = 6.80;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Pencil Case: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonBoxActionPerformed

    private void jButtonCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculatorActionPerformed
        double priceOfItem = 15.90;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Calculator: 1 set", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonCalculatorActionPerformed

    private void jButtonDucttapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDucttapeActionPerformed
        double priceOfItem = 1.60;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Duct Tape: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonDucttapeActionPerformed

    private void jButtonTapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTapeActionPerformed
        double priceOfItem = 1.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Sellotape(Clear): 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonTapeActionPerformed

    private void jButtonGlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGlueActionPerformed
        double priceOfItem = 2.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Glue: 1 bottle", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonGlueActionPerformed

    private void jButtonStapletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStapletActionPerformed
        double priceOfItem = 0.50;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Staplet: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonStapletActionPerformed

    private void jButtonBrushesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrushesActionPerformed
        double priceOfItem = 1.70;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Watercolor brush: 1 box", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonBrushesActionPerformed

    private void jButtonPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaperActionPerformed
        double priceOfItem = 18.50;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"A4 Paper: 1 unit", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonPaperActionPerformed

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
        double priceOfItem = 1.10;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {"Excercise Book: 1 pcs", "1", priceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonBookActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jTextChange.setText("");
        jTextDiscount.setText("");
        jTextTotal.setText("");
        jTextSubtotal.setText("");
        jTextDisplay.setText("");
        
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jTextChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextChangeActionPerformed
        
    }//GEN-LAST:event_jTextChangeActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, interger}");
        
        try {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        
        } catch (PrinterException ex) {
            System.err.format("No printer found!", ex.getMessage());
            //Logger.getLogger(CashierApp.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int RemoveItem = jTable1.getSelectedRow();
        
        if (RemoveItem >= 0) {
            model.removeRow(RemoveItem);
        }
        ItemCost();
        
        if (jComboPayment.getSelectedItem().equals("Cash")) {
            Change();
        } 
        
        else {
            jTextChange.setText("");
            jTextDisplay.setText("");
        }
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jTextSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSubtotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton00;
    private javax.swing.JButton jButton01;
    private javax.swing.JButton jButton02;
    private javax.swing.JButton jButton03;
    private javax.swing.JButton jButton04;
    private javax.swing.JButton jButton05;
    private javax.swing.JButton jButton06;
    private javax.swing.JButton jButton07;
    private javax.swing.JButton jButton08;
    private javax.swing.JButton jButton09;
    private javax.swing.JButton jButtonBook;
    private javax.swing.JButton jButtonBox;
    private javax.swing.JButton jButtonBrushes;
    private javax.swing.JButton jButtonCalculator;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCaryon;
    private javax.swing.JButton jButtonCharcoal;
    private javax.swing.JButton jButtonColorPencil;
    private javax.swing.JButton jButtonDucttape;
    private javax.swing.JButton jButtonEraser;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonFountain;
    private javax.swing.JButton jButtonGlue;
    private javax.swing.JButton jButtonLead;
    private javax.swing.JButton jButtonMarker;
    private javax.swing.JButton jButtonMechanical;
    private javax.swing.JButton jButtonPaper;
    private javax.swing.JButton jButtonPay;
    private javax.swing.JButton jButtonPen;
    private javax.swing.JButton jButtonPencil;
    private javax.swing.JButton jButtonPeriod;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonScissors;
    private javax.swing.JButton jButtonSharpener;
    private javax.swing.JButton jButtonStapler;
    private javax.swing.JButton jButtonStaplet;
    private javax.swing.JButton jButtonTape;
    private javax.swing.JButton jButtonWatercolor;
    private javax.swing.JComboBox<String> jComboPayment;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextChange;
    private javax.swing.JTextField jTextDiscount;
    private javax.swing.JTextField jTextDisplay;
    private javax.swing.JTextField jTextSubtotal;
    private javax.swing.JTextField jTextTotal;
    // End of variables declaration//GEN-END:variables
}
